# Generated by Django 4.2.6 on 2023-10-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/default_picture_event.png', upload_to='images/events')),
                ('start_data', models.DateTimeField()),
                ('event_link', models.URLField(blank=True, null=True)),
                ('cterate_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_gallery', models.ImageField(upload_to='images/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAndStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('info', models.TextField()),
                ('email_link', models.EmailField(max_length=250)),
                ('image', models.ImageField(default='images/default_picture_tands.png', upload_to='images/tands')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ST', 'Student'), ('TC', 'Teacher')], max_length=2)),
                ('cterate_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/default_picture_project.png', upload_to='images/projects')),
                ('project_link', models.URLField(blank=True, null=True)),
                ('cterate_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.courses')),
                ('technologies', models.ManyToManyField(to='addinfo.technology')),
            ],
        ),
    ]
