# Generated by Django 4.2.7 on 2023-11-03 18:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacherandstudent',
            name='info',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
