# Generated by Django 4.2.7 on 2023-11-03 18:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addinfo', '0002_alter_events_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
