# Generated by Django 4.2.7 on 2023-11-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
        ('addinfo', '0002_alter_events_start_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherandstudent',
            name='course',
        ),
        migrations.AlterField(
            model_name='teacherandstudent',
            name='email_link',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacherandstudent',
            name='course',
            field=models.ManyToManyField(to='certificate.courses'),
        ),
    ]
