# Generated by Django 4.2.7 on 2023-11-10 11:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[accounts.models.CustomUser.validate_integer]),
        ),
    ]
