# Generated by Django 4.2.7 on 2023-11-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
