# Generated by Django 4.2.7 on 2023-11-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sendmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmail',
            old_name='tite',
            new_name='title',
        ),
    ]
