# Generated by Django 4.2.6 on 2023-10-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='images/default_picture_project.png', upload_to='images/blogs'),
        ),
    ]
