# Generated by Django 4.2.6 on 2023-10-22 11:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='tag',
        ),
        migrations.AddField(
            model_name='blogs',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], default=0, max_length=200),
        ),
    ]
