# Generated by Django 4.2.6 on 2023-10-22 13:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogs_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'qarshi'), (2, 'jumali'), (3, 'Shaxboz'), (4, 'london'), (5, 'Samandarbek')], default=0, max_length=3),
        ),
    ]
