# Generated by Django 4.2.6 on 2023-10-22 15:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogs_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'qarshi'), (2, 'jumali'), (3, 'Shaxboz'), (4, 'london'), (5, 'Samandarbek'), (7, 'elif')], default=0, max_length=3),
        ),
    ]
